---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5e9490a7e3c7e0001350ef23/webhook/forestry
sections:
- type: heading
  label: Le coin des complotistes
- type: heading
  label: Blind Test
- type: heading
  label: Tabou
- type: heading
  label: Pictionary
- type: heading
  label: Cherche et trouve
- type: heading
  label: Créa-room
- type: heading
  label: Curvytron
- type: document
  path: config.yaml
  label: Global Site Config
  templates:
  - config
- type: document
  path: data/author.json
  label: Author
  templates:
  - author
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: directory
  path: content
  label: Page
  create: all
  match: "**/*"
  exclude: "{posts/**,_index.md,contact.md}"
  templates:
  - page
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.47'
